### ISSUE TITLE
Add to Package Control

### ISSUE THREAD

**Issue by SeanGroff** [VonHeikemen/night-owl-sublime-scheme#1]
Awesome work!!!!! 💯 
Do you plan on adding this to [packagecontrol.io](https://packagecontrol.io/)?

**Comment by VonHeikemen** [comment]
Thanks.

Yes, there is a pull request in process to add it to the default channel.

**Comment by VonHeikemen** [comment]
Pull request was merged. You can now install it using Package Control, searching by the name "Night Owl"

https://packagecontrol.io/packages/Night%20Owl

**Comment by alexmccabe** [comment]
Still not available in-app
