### ISSUE TITLE
Doesn't syntax highlight JSX correctly

### ISSUE THREAD

**Issue by SeanGroff** [VonHeikemen/night-owl-sublime-scheme#2]
Syntax highlighting is off for JSX. See screenshots and details below.

Here's how the JSX currently looks

![screen shot 2019-01-08 at 4 16 35 pm](https://user-images.githubusercontent.com/4367312/50862519-72c85d80-1361-11e9-8ce5-74a952a661ae.png)

When comparing to the official Night Owl theme in VS Code there are a few differences: 

* Custom React component elements have Orange text
* html attributes in JSX are light green
* variable names are blue

Here are a couple screenshots from VS Code as reference:

![screen shot 2019-01-08 at 4 17 13 pm](https://user-images.githubusercontent.com/4367312/50862774-24678e80-1362-11e9-913b-3ad8cc69e936.png)

![screen shot 2019-01-08 at 4 18 14 pm](https://user-images.githubusercontent.com/4367312/50862783-27fb1580-1362-11e9-8cce-dac948fc5380.png)

Thanks for porting this theme to ST3 you did a great job 👍

**Comment by VonHeikemen** [comment]
The colors actually depends on the syntax highlight plugin that you use, they assign a scope to each element which is what the color scheme uses to assign the correct colors. 

By default it has support for the [Simple JSX](https://packagecontrol.io/packages/Simple%20JSX) plugin. If you can tell me what plugin you use for JSX I can try support that.

I actually use (and support) [VSCode's syntax definition](https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json) for JSX, I've converted it from JSON to XML plist format (using [this](https://packagecontrol.io/packages/PackageDev)) and saved it in my User folder `Packages/User` as JavaScriptReact.tmLanguage

**Comment by SeanGroff** [comment]
I didn't know about the Simple JSX plugin as I've always used the [Babel](https://packagecontrol.io/packages/Babel) plugin to handle my JS and JSX syntax highlighting. I replaced the Babel plugin with Simple JSX now I have the correct syntax highlighting :-)
Thanks!!

**Comment by VonHeikemen** [comment]
I was able to add the support necessary for the Babel plugin. If you want to test it now you'll have to download the file from the master branch. I will release the next version with the changes tomorrow.

EDIT: v0.2.0 is out now!

The code in JSX should now look like this.
![2019-01-09-183234_805x696_scrot](https://user-images.githubusercontent.com/20980671/50934592-7205f900-143f-11e9-94ab-3b62e0dbab05.png)
