### ISSUE TITLE
For another editor

### ISSUE THREAD

**Issue by Alexey-T** [VonHeikemen/night-owl-sublime-scheme#5]
Hi, nice color scheme. Is it possible to make syntax-theme (no UI-theme needed) for CudaText?
http://wiki.freepascal.org/CudaText#Color_themes

**Comment by VonHeikemen** [comment]
I can help with that. I published a gist with the syntax config [here](https://gist.github.com/VonHeikemen/bcd16ebba5a53af8003c905cbb73c62c).

Made a few modifications to the ebony theme to make look more like night owl. Almost all languages look good, except for python. To make look consistent in python I had to map the lexer style of `Id Keyword -- IdKeyword`  (the default is `Id Keyword -- Id1`)

**Comment by Alexey-T** [comment]
Thank you. I’ve published it in Addon manager.
