### ISSUE TITLE
Italics support

### ISSUE THREAD

**Issue by devansvd** [VonHeikemen/night-owl-sublime-scheme#6]
It would be nice if this plugin supports italics like the  [sarah's vscode theme](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl).

Thanks for porting it.

**Comment by VonHeikemen** [comment]
There is some support for italics, it's just not like the VScode theme. To be honest I don't want to put italics in every place the original theme has them.

**Comment by devansvd** [comment]
@VonHeikemen it is turned on by default or have to do  any configuration ?

**Comment by VonHeikemen** [comment]
by default only comments and tag attributes are italics.

Now that you mention configuration, there is something you can do: create a `Night Owl.sublime-color-scheme` file (is like a json file) in your `User` package folder, next thing is overwrite the rules of the theme. For example to enable italics for function names you copy this.

```
{
  "rules": [
    {
      "name": "Function",
      "scope": "variable.function, support.function",
      "foreground": "var(blue)",
      "font_style": "italic"
    },
  ]
}
```

You can do it with any rule in the theme and even color of the variables, you have to copy/paste the rule from the theme and add ` "font_style": "italic"`. I actually overwrite some rules in my config, you can check my [dotfile repo](https://github.com/VonHeikemen/dotfiles/blob/master/.config/sublime-text-3/Packages/User/Night%20Owl.sublime-color-scheme)

**Comment by devansvd** [comment]
Hey !  Thanks this is really helpful, will check this out.
